version: '3.8'

services:
  springboot:
    build: .
    container_name: springboot_app_dev
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_DATA_REDIS_HOST=redis_cache_dev
      - SPRING_DATA_REDIS_PORT=6379
    restart: on-failure

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache_dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  redis-data-dev: