version: '3.8'

services:
  springboot:
    build: .
    container_name: springboot_app_dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=host.docker.internal
      - SPRING_DATA_REDIS_PORT=6379
    restart: on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
