version: '3.8'

services:
  springboot:
    build: .
    container_name: springboot_app_dev
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache_dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data

volumes:
  redis-data-dev:
