version: '3.8'

services:
  springboot:
    build: .
    container_name: springboot_app_dev
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=<EC2_HOST_IP_OR_LOCALHOST>
      - SPRING_DATA_REDIS_PORT=6379
    restart: on-failure