spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Encorely?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: a12752411!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: never

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        enabled: true

  data:
    redis:
      host: redis
      port: 6379

  jwt:
    secret-key: my-super-very-secret-jwt-key-local-999

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

custom:
  s3:
    bucket: encorely

springdoc:
  swagger-ui:
    urls:
      - name: prod
        url: http://3.34.105.231:8080/v3/api-docs
      - name: dev
        url: http://13.209.39.26:8080/v3/api-docs
      - name: local
        url: http://localhost:8080/v3/api-docs