name: Deploy to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ubuntu
      EC2_KEY: ${{ secrets.EC2_KEY }}
      EC2_MAIN_HOST: ${{ secrets.EC2_MAIN_HOST }}
      EC2_DEV_HOST: ${{ secrets.EC2_DEV_HOST }}
      APPLICATION_YML_PROD: ${{ secrets.APPLICATION_YML_PROD }}
      APPLICATION_YML_DEV: ${{ secrets.APPLICATION_YML_DEV }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set deployment variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "HOST=${EC2_MAIN_HOST}" >> "$GITHUB_ENV"
            echo "YML_CONTENT=${APPLICATION_YML_PROD}" >> "$GITHUB_ENV"
            echo "DOCKER_YML=docker-compose.main.yml" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "HOST=${EC2_DEV_HOST}" >> "$GITHUB_ENV"
            echo "YML_CONTENT=${APPLICATION_YML_DEV}" >> "$GITHUB_ENV"
            echo "DOCKER_YML=docker-compose.develop.yml" >> "$GITHUB_ENV"
          fi

      - name: Create pem file
        run: echo "$EC2_KEY" | base64 -d > ec2-key.pem && chmod 600 ec2-key.pem

      - name: Copy code to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST << EOF
            cd ~/app
            git fetch origin
            git checkout ${GITHUB_REF##*/}
            git pull origin ${GITHUB_REF##*/}
          EOF

      - name: Upload application.yml
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST << EOF
            mkdir -p ~/app/src/main/resources
            echo "$YML_CONTENT" | base64 -d > ~/app/src/main/resources/application.yml
          EOF

      - name: Rebuild and restart container
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST << EOF
            cd ~/app
            docker compose -f $DOCKER_YML down
            docker compose -f $DOCKER_YML up --build -d
          EOF
