name: Deploy to EC2

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_USER: ubuntu
      EC2_KEY: ${{ secrets.EC2_KEY }}
      EC2_MAIN_HOST: ${{ secrets.EC2_MAIN_HOST }}
      EC2_DEV_HOST: ${{ secrets.EC2_DEV_HOST }}
      APPLICATION_YML_PROD: ${{ secrets.APPLICATION_YML_PROD }}
      APPLICATION_YML_DEV: ${{ secrets.APPLICATION_YML_DEV }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set deployment variables
        id: vars
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "HOST=${EC2_MAIN_HOST}" >> "$GITHUB_ENV"
            echo "DOCKER_YML=docker-compose.main.yml" >> "$GITHUB_ENV"
            echo "${APPLICATION_YML_PROD}" > yml.txt
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "HOST=${EC2_DEV_HOST}" >> "$GITHUB_ENV"
            echo "DOCKER_YML=docker-compose.develop.yml" >> "$GITHUB_ENV"
            echo "${APPLICATION_YML_DEV}" > yml.txt
          fi

      - name: Create pem file
        run: |
          echo "$EC2_KEY" | base64 -d > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Copy project files and application.yml to EC2
        run: |
          rsync -av -e "ssh -i ec2-key.pem -o StrictHostKeyChecking=no" --exclude='.git' --delete ./ $EC2_USER@$HOST:~/app/
          scp -i ec2-key.pem -o StrictHostKeyChecking=no yml.txt $EC2_USER@$HOST:~/app/application.yml.b64
      - name: Setup application.yml and restart container on EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST base64 -d /home/ubuntu/app/application.yml.b64 > /home/ubuntu/app/src/main/resources/application.yml
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST docker compose -f ~/app/$DOCKER_YML down
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no $EC2_USER@$HOST docker compose -f ~/app/$DOCKER_YML up --build -d
